# Configuration éditoriale minimale
site_title: "Newsletter Echome Energies — Photovoltaïque"
brand_color: "#37C3AF"   # turquoise Echome
text_color: "#1C1C1C"
blocks:
  - edito
  - actu_reglementaire
  - chiffre_du_mois
  - cas_concret
  - conseil_pratique
  - contact_cta

blocks:
  - edito
  - actu_reglementaire
  - barometre_cre      # 👈 nouveau
  - pedagogie_msb      # 👈 nouveau
  - contact_cta

links:
  cre_t3_2025: "https://www.cre.fr/Actualites"   # (ou colle l’URL exacte du PDF/actu CRE T3 2025)
  msb_visual: "msb-visuel.jpg"                   # (on uploadera l’image juste après)

links:
  legifrance_s21: "https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000051380903"
  edf_oa_s21: "https://www.edf-oa.fr/content/contrat-de-type-s21"
  enedis_raccord: "https://www.enedis.fr/je-raccorde-une-installation-de-production-delectricite"
